image:
  tag: "sha-cbb6bc0519bb"
replicaCount: 1
service:
  port: 80
  targetPort: 8080
env:
  - name: APP_ENV
    value: dev
  - name: APP_VERSION
    value: unversioned
  - name: GIT_SHA
    value: "cbb6bc0519bb"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
ingress:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
  host: ""
  paths:
    - path: "/"
      pathType: Prefix
probes:
  enabled: true
  path: "/healthz"
  port: 8080
